# Generated by Django 5.2.17 on 2026-09-25 08:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('rating', models.CharField(default='0', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'service_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('content_type', models.CharField(max_length=32)),
                ('duration_or_read_time', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('content_details', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('quiz_questions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'training_modules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vet_profiles',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_vet_recommendation', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_location', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_posts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_rows', to='core.communitypost')),
            ],
            options={
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('farm_name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('farm_size', models.CharField(blank=True, default='', max_length=64)),
                ('chicken_type', models.CharField(blank=True, default='', max_length=128)),
                ('total_chickens', models.IntegerField(default=0)),
                ('housing_system', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='Salama / Operational', max_length=64)),
                ('qr_code_data', models.CharField(blank=True, default='', max_length=128)),
                ('setup_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_profiles',
            },
        ),
        migrations.CreateModel(
            name='FeedInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('current_stock_kg', models.FloatField(default=0)),
                ('total_capacity_kg', models.FloatField(default=500)),
                ('type', models.CharField(max_length=64)),
                ('cost_per_kg', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_inventory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(blank=True, default='', max_length=32)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_for_sale', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoultryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('age', models.CharField(blank=True, default='', max_length=64)),
                ('date_purchased', models.DateTimeField()),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poultry_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poultry_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('eggs', models.IntegerField(default=0)),
                ('feed_kg', models.FloatField(default=0)),
                ('water_liters', models.FloatField(default=0)),
                ('mortality', models.IntegerField(default=0)),
                ('bird_avg_weight_kg', models.FloatField(default=0)),
                ('expenses_tsz', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_logs',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SickChickenReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symptoms_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnoses/')),
                ('image_or_video_url', models.URLField(blank=True, default='')),
                ('diagnosed_disease', models.CharField(max_length=255)),
                ('confidence_level', models.CharField(max_length=16)),
                ('recommended_action', models.TextField()),
                ('recommended_medicines', models.JSONField(default=list)),
                ('urgency', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_chicken_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sick_chicken_reports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='sw', max_length=8)),
                ('vaccine_notifications', models.BooleanField(default=True)),
                ('disease_alerts', models.BooleanField(default=True)),
                ('market_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='VaccinationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('target_age', models.CharField(blank=True, default='', max_length=64)),
                ('scheduled_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(default='vaccine', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset', 'Reset password')], max_length=16)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_codes',
                'indexes': [models.Index(fields=['identifier', 'purpose', 'is_used'], name='verificatio_identif_55c4d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VetConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vet_name', models.CharField(max_length=255)),
                ('consultation_type', models.CharField(max_length=64)),
                ('requested_time', models.DateTimeField()),
                ('symptoms_or_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Pending', max_length=64)),
                ('doctor_prescription', models.TextField(blank=True, default='')),
                ('uploaded_media', models.FileField(blank=True, null=True, upload_to='consultations/')),
                ('uploaded_media_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_consultations', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.vetprofile')),
            ],
            options={
                'db_table': 'vet_consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.communitypost')),
            ],
            options={
                'db_table': 'community_likes',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
